# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  labels:
    app: default-init
data:
  entrypoint.sh: |
    #!/usr/bin/env bash

    set -euo pipefail

    DEBIAN_FRONTEND=noninteractive
    ROOT_MOUNT_DIR="${ROOT_MOUNT_DIR:-/root}"

    # We use chroot to run the following commands in the host root (mounted as the /root volume in the container)
    
    # newvalues - what we'll add to the daemon.json
    newvalues='"log-opts":{\n"max-size": "5m",\n"max-file": "3" }\n'
    filename='/etc/docker/daemon.json'
    
    # We'll insert the log-opts after this line
    match='"storage-driver": "overlay2"'
    
    # We'll remove those values from /etc/default/docker - or the daemon will NOT be happy (set in 2 places)
    rem='--log-opt=max-size=10m --log-opt=max-file=5 '
    echo "Amend daemon.json"
    chroot "${ROOT_MOUNT_DIR}" sed "/$match/a\,\n$newvalues" $filename
    echo "Amend /etc/default/docker"
    chroot "${ROOT_MOUNT_DIR}" sed -i "s/$rem//" /etc/default/docker
    echo "restart docker"
    chroot "${ROOT_MOUNT_DIR}" systemctl restart docker
